## Trap RF Map

### 9/20/16

We needed to creat a RF map so we can set the rf on one rod and the other rods amplitude and phase adjust to match the waveform. I wrote an optimization program to do this. It uses a keysight sequence to grab the tracec and fit the amplitude, phase, and offset. Each iteration channel 2 is fixed and channel 3 is matched. As of now the scale on the oscilloscope needs to be changed as you scan throught the voltages so the traces do not exceed the top and bottom of the screen. Because of this the map was made in four different files. Will stitch them together and put the map in the server file. 

In [1]:
# Read in traces

rf_50_100 = np.loadtxt('C:/Users/barium133/Code/barium/lib/scripts/Oscilloscope/rf_settings_50_100.txt')
rf_101_400 = np.loadtxt('C:/Users/barium133/Code/barium/lib/scripts/Oscilloscope/rf_settings_101_400.txt')
rf_401_700 = np.loadtxt('C:/Users/barium133/Code/barium/lib/scripts/Oscilloscope/rf_settings_401_700.txt')
rf_701_1000 = np.loadtxt('C:/Users/barium133/Code/barium/lib/scripts/Oscilloscope/rf_settings_701_1000.txt')
rf_1001_1233 = np.loadtxt('C:/Users/barium133/Code/barium/lib/scripts/Oscilloscope/rf_settings_1001_1233.txt')


rf_map = np.append(rf_50_100, rf_101_400,  axis = 0)
rf_map = np.append(rf_map, rf_401_700 , axis = 0)
rf_map = np.append(rf_map, rf_701_1000 , axis = 0)
rf_map = np.append(rf_map,rf_1001_1233 , axis = 0)

np.savetxt('C:/Users/barium133/Code/barium/lib/clients/TrapControl_client/rf_map.txt',rf_map,fmt="%0.2f")

print rf_map

[[   50.     49.     22.2]
 [   51.     51.     22. ]
 [   52.     51.     22. ]
 ..., 
 [ 1231.   1226.     11.3]
 [ 1232.   1227.     11.3]
 [ 1233.   1229.     11.3]]


## 